name: test
on:
- pull_request
jobs:
  xenial-5-1:
    container:
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --sanitize=thread
  bionic-5-1:
    container:
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --sanitize=thread
