name: test
on:
- pull_request
jobs:
  address:
    container:
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --sanitize=address
